### ISSUE TITLE
Launch blockers

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#1]
- Port the front page from kub.unitedcreations.xyz to kubernetes.github.io repo. Looks like it's done. The lorem ipsum is fine, we'll handle it. The layout named "headerfooter" is all set up for marketing page use, so all you should need to do is slot in the case studies instead of the docs nav, and the content body.
- Remove uses of the Pi JavaScript library in favor of jQuery
- Check in your SASS partials into the repo under the folder _sass; here are instructions if this is not clear.
- CSS issue: Lists are "bumping up" against content too closely on their top margin. ex: http://kubernetes.github.io/v1.1/docs/getting-started-guides/meanstack/ and here.
- CSS issue: List spacing is very tall between top-tier items, but crowded on second tier items: http://kubernetes.github.io/v1.1/docs/user-guide/known-issues/
- CSS issue: Lists have a different font (see http://kubernetes.github.io/v1.1/docs/user-guide/known-issues/)
- CSS issue: hyperlinked/in-line code items should give users more of a hint -- suggest they at least turn blue. (See the programmatic objects in the in-page TOC http://kubernetes.github.io/v1.1/docs/getting-started-guides/meanstack/)
- CSS issue: All code examples are double-spaced. (See code examples on same page)
- CSS issue: Code examples wrap awkwardly instead of creating a scrollable area. ex: http://kubernetes.github.io/v1.1/docs/user-guide/configuring-containers/ (see line re: "false alarm" vs something like https://github.com/kubernetes/kubernetes.github.io/blob/master/v1.1/docs/user-guide/production-pods.md) 
- CSS issue: Tables are completely unformatted! Scroll to bottom of this page: http://kubernetes.github.io/v1.1/docs/user-guide/jsonpath/
- CSS nice-to-have: I just copy/pasted the GitHub Blog's default syntax.css values for code syntax highlighting, and it's very black-and-red which is not necessarily the color scheme of the site. If a designer with a bit of time could tweak these values to be more on-brand (the ".highlight .s"-type classes) then that would be awesome.
- Re: The Community page: I'm guessing the best we can do for content here is porting the old HTML from the current k8s.io, so please do. 
- Are we really dropping "Media" and "Events?"

**Comment by johndmulhausen** [comment]
CC @CreaturesInUnitards

**Comment by CreaturesInUnitards** [comment]
Addressed 8 of the 13 above. Some comments and questions inline:

- Check in your SASS partials into the repo under the folder _sass **DONE**

- CSS issue: Lists are "bumping up" against content too closely on their top margin **DONE**

- CSS issue: List spacing is very tall between top-tier items, but crowded on second tier items **DONE** **do you want this tightened up more?**

- CSS issue: Lists have a different font **DONE**

- CSS issue: hyperlinked/in-line code items should give users more of a hint **DONE — added blue and underlines**

- CSS issue: All code examples are double-spaced. **DONE**

- CSS issue: Code examples wrap awkwardly instead of creating a scrollable area. **DONE**

- CSS issue: Tables are completely unformatted! **DONE — added minimal formatting, can take it further if you want**

**Comment by johndmulhausen** [comment]
Google DevDocs standard table example: https://developers.google.com/analytics/devguides/collection/android/v4/events

**Comment by johndmulhausen** [comment]
"made better text suggestions" -> "enter your wish"
keycode 13 intercepted by search

**Comment by CreaturesInUnitards** [comment]
code block headings
search result stroke

**Comment by johndmulhausen** [comment]
Re: CSS issue: List spacing is very tall between top-tier items, but crowded on second tier items DONE do you want this tightened up more?

It's a little widely spaced, yes. Love that it's uniform now between tiers, but tighter would probably be better, don't you think?

**Comment by CreaturesInUnitards** [comment]
I'm closing this one — everything here is now broken out individually
