### ISSUE TITLE
I wish /third_party/swagger-ui/ existed!!!

### ISSUE THREAD

**Issue by tizhou86** [kubernetes/kubernetes.github.io#112]
I wish /third_party/swagger-ui/ existed!!!

**Comment by ipedrazas** [comment]
Yep, it used to exist... but it has vanished... :sob:

**Comment by bgrant0607** [comment]
API references for 1.2 are mostly available:

http://kubernetes.io/docs/api-reference/v1/definitions/
http://kubernetes.io/docs/api-reference/v1/operations/
http://kubernetes.io/docs/api-reference/extensions/v1beta1/operations/
http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/

Is there a reason you prefer the swagger UI? It has performance and security problems.

cc @nikhiljindal @caesarxuchao @johndmulhausen

**Comment by onorua** [comment]
I prefer swagger-ui because I could see all the APIs in one place, this place was always working, even I do not have api-server up and running. 
This references and definitions is good if you want to build manifest from 0. 
If you want to fix someone's improper manifest - it has 0 usage. You have description the same as swagger but you don't have structure. You can get the structure by reading all the lines, and building it in your head, instead of just open the json output, check whether you need to setup DNS policy within Container or with the POD. It was easy to fix issues with syntax with just glance view, right now, I must run api-server VM to have it. Which is obviously regression :(

**Comment by caesarxuchao** [comment]
Hi @onorua, if I understand you correctly, what you'd like to see is the "Model Schema" feature of swagger-ui, which has the structure, am I right?
![image](https://cloud.githubusercontent.com/assets/2823529/13838158/e7f254e8-ebce-11e5-801a-328c5a4c7a68.png)

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by onorua** [comment]
@caesarxuchao yes, exactly!

**Comment by nikhiljindal** [comment]
@johndmulhausen Lots of users are reporting this error. Any idea how to fix this?

**Comment by ipedrazas** [comment]
The problem, I think, it's that Google returns the swagger page where you search for kubernetes api.

**Comment by lavalamp** [comment]
We can put it back up if there's a version without XSS vulnerabilities. Is that the case?

**Comment by johndmulhausen** [comment]
Added forwarding to 404.md that sends users to the new URL:
http://kubernetes.io/kubernetes/third_party/swagger-ui/

**Comment by bgrant0607** [comment]
The swagger UI is VERY SLOW, due to the size of our swagger spec. I liked it at the time I added it, but now find it unusable.
