### ISSUE TITLE
Links pointing to release-1.3 branch which does not exist

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes.github.io#1269]
All the links in the documentation are pointing to `release-1.3` branch. To name a few:
- http://kubernetes.io/docs/user-guide/connecting-applications/ is pointing to `run-my-nginx.yaml` ->  https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/release-1.3/docs/user-guide/run-my-nginx.yaml
- http://kubernetes.io/docs/user-guide/jobs/, pointing to `job.yaml` -> https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/release-1.3/docs/user-guide/job.yaml

@devin-donnelly could we create such a branch or you prefer to wait for 1.4 and have it working then?

**Comment by rnaveiras** [comment]
@soltysh @devin-donnelly the links are broken because when they are generated are using the variables defined in `_config.yml`, The branch `release-1.3` no longer exist so `raw.githubusercontent.com` return not found.

```yaml
    values:
      version: "v1.3"
      githubbranch: "master"
      docsbranch: "release-1.3"
```

See here:
- https://github.com/kubernetes/kubernetes.github.io/blob/master/_config.yml#L19-L21 
- https://github.com/kubernetes/kubernetes.github.io/blob/master/_includes/code.html

A simple solution will change that variable to `docsbranch: "master"`

Let me know if you are happy with this solution and will send a PR with the change.

**Comment by rnaveiras** [comment]
Linking this issue too because is the same problem https://github.com/kubernetes/kubernetes.github.io/issues/1249 related with the deletion of `release-1.3` branch

**Comment by soltysh** [comment]
I wouldn't mind, but I guess this is intentionally, to show latest stable release. The problem here (I think) is that 1.3 branch was prematurely removed, but @devin-donnelly will be best to confirm that.

**Comment by devin-donnelly** [comment]
@rnaveiras , I would prefer that fix. We currently are not hosting versioned docs, so that configuration is obsolete. Go ahead and send out the PR and I'll merge it ASAP.

**Comment by Starefossen** [comment]
Should we perhaps bump the page.version to v1.4? 

```
values:
      version: "v1.4"
      githubbranch: "master"
      docsbranch: "master"
```
