### ISSUE TITLE
Use netlify to deploy docs & get subdomains for branches

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/kubernetes.github.io#1371]
**This is a...** 

- [x ] Feature Request

**Problem:**
Right now we are using github pages for the actual deploy of docs and we have separate branches per versions. 

**Proposed Solution:**
Use netlify which is already setup for PRs to host docs as well. It can do branches as subdomains and we get automatic free SSL https://www.netlify.com/docs/continuous-deployment/

**Page to Update:**
http://kubernetes.io/...

ping @calavera I'm pretty sure this should just be a few clicks in the netlify backend and changes to config :)

**Comment by calavera** [comment]
This should be pretty straightforward for the main site. However, we're releasing something tomorrow to make it even more easy to create subdomains for branches and link DNS records to them. I can definitely help with this. Is there any other channel we can use to have a more direct conversation? IRC?

**Comment by calavera** [comment]
We just released our new domain dashboard to help with subdomain configurations, you can read more in the blog post https://www.netlify.com/blog/2016/10/06/introducing-our-domain-dashboard/

## The easy way

How is that feature useful?

1. We use what NS1 calls "linked records" to configure DNS records. This means that the records for kubernetes.io are linked to ours. Since our records are already propagated, there is no downtime when you change DNS name servers in the domain provider.

2. It makes very easy to have subdomains for branches and keep TLS certificates up to date. You basically select a branch you want to expose as a subdomain and we create the DNS record and add a new name to the TLS certificate provisioned for kubernetes.io


## The slightly longer way

You can also do all this manually, these are the steps:

1. Create a site in Netlify and link to this GitHub repository's master branch. (This is already done, I believe)
2. Add the custom domain but without letting Netlify manage it.
3. Add a CNAME record for the www domain:
www.kubernetes.io    CNAME   kubernetes-io.netlify.com
4. Add an A record to our main load balancer for apex domains:
kubernetes.io       A       104.198.14.52

That should be it for the main site. Please, read this post to understand why setting www records is important if you have questions about step 3: https://www.netlify.com/blog/2016/01/12/this-weekends-ddos-attack-and-whats-in-a-cname/

When this is done, each time changes are merged in master, Netlify deploys those changes to kubernetes.io.

### Manual setup for subdomain branches

Setting up subdomains for release branches is a matter of setting up CNAME records. For instance, if you want to have `release-1-4.kubernetes.io` you need to create this record:

release-1-4.kubernetes.io     CNAME  release-1-4--kubernetes-io.netlify.com

With TLS enabled, setting up branch subdomains require an extra step, release-1-4.kubernetes.io needs to be added to the site domain aliases: https://www.netlify.com/docs/custom-domains/#domain-aliases to tell Let's Encrypt that the subdomain is also a valid name for the certificate.


Please, let me know if you have any questions, I'll be super happy to help.

**Comment by chenopis** [comment]
I'm targeting 2017Q3 to move k8s.io prod over to Netlify.

**Comment by chenopis** [comment]
This has been completed.
