### ISSUE TITLE
Documentation does not work for user project page on gh-pages branch

### ISSUE THREAD

**Issue by rothgar** [kubernetes/kubernetes.github.io#173]
Following the [github documentation for project pages](https://help.github.com/articles/user-organization-and-project-pages/) I tried forking the docs and committing changes to my gh-pages branch. After doing that the pages do not render properly and links try to revert to my [user pages repo](rothgar.github.io).

![image](https://cloud.githubusercontent.com/assets/371796/13869501/b9f3f9c4-ec92-11e5-8dc1-e15e09cec9cc.png)

You can view my fork at https://rothgar.github.io/kubedocs and see that links are broken. I'm opening this issue to figure out why this is happening and track the issue.

Once the links are fixed we should also update documentation for contributing so other users can push to their gh-pages branch in case they already have user pages.

**Comment by rothgar** [comment]
Only thing I can think of to solve the need for a CNAME file is to have users delete it from their gh-pages branch but then submit PRs from a different branch. It'd be an extra step and sometimes hard to verify the pages work correctly but would be nice to allow project pages for users by default instead of requiring them to use <username>.github.io

**Comment by johndmulhausen** [comment]
We do actually say people should remove the CNAME file and use .github.io, which is why CNAME is listed in .gitignore. We want to use absolute links for many reasons, so this is unlikely to ever work for a context other than .github.io remotely. It's only a few commands to get the repo working on local staging. We don't document or support creating a gh-pages branch, so it's expected that it doesn't work. Sorry to bear bad news, but if deleting CNAME or running gem install github-pages locally and working there is really too tough ping me with a proposal.
