### ISSUE TITLE
I wish /docs/hellonode/ Could Say deleting the project stops the billing instantley

### ISSUE THREAD

**Issue by rolandkofler** [kubernetes/kubernetes.github.io#201]
I wish /docs/hellonode/ Could Say deleting the project stops the billing instantley

**Comment by johndmulhausen** [comment]
It implies as much. "Of course, you can also delete the entire project but note that you must first disable billing on the project. Additionally, deleting a project will only happen after the current billing cycle ends."

Since it's not true that it stops billing "instantly" so much as, "it marks the project as unauthorized for new billing changes and leaves it active until then," this is the most true information we can say. Feel free to send a PR with suggest reword if you still think it's awkward. :)
