### ISSUE TITLE
Refdocs have crowding btx headings/tables / man pages are awful

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#22]
Could be an issue around tables not having proper spacing?

http://kubernetes.github.io/v1.1/docs/api-reference/v1/definitions/
http://kubernetes.github.io/v1.1/docs/api-reference/v1/operations/

Lots of instances where tables/headings are bumping against each other.

In other refdoc news, I know we talked about making the code examples scroll, but check out what's going on in the man pages for the CLI:

http://kubernetes.github.io/v1.1/docs/admin/kube-apiserver/

Is there a graceful way to line wrap with indenting -- just in this one case? If too gnarly, no worries.
cc @CreaturesInUnitards

**Comment by CreaturesInUnitards** [comment]
ok, I'm giving tables (excluding search results) 60px margin-bottom.

As for the indented line wrap in the case of the cli manpages, _yes_, it's possible, but allow me to try to talk you off the ledge: the ugly, cut-off appearance for lines that horizontally overflow a code block is expected behavior. No, it's not beautiful, but consider:

http://stackoverflow.com/questions/35656896/sql-select-between-two-spaces-or-everything-after-first-if-only-one
http://stackoverflow.com/questions/35657082/sagepay-direct-3dsecure-checkout-part-returning-blank-page-when-redirecting-out

I honestly don't think K8s users are expecting anything different; in fact I think wrapping could be confusing, even if the wrapped lines are indented.

That said, if you really want to do it, then yes, it can be done. We just need a reliable way to categorically identify the offending code blocks, and I can make it happen.

**Comment by johndmulhausen** [comment]
Both seem to look good. Scrollbars + table.
