### ISSUE TITLE
HTTPS->HTTP->HTTPS redirection

### ISSUE THREAD

**Issue by ahmetalpbalkan** [kubernetes/kubernetes.github.io#2305]
`https://kubernetes.github.io/` redirects to `http://kubernetes.io/` which redirects to `https://kubernetes.io/`. Is it possible to make the github.io subdomain redirect directly to https?

**Comment by jaredbhatti** [comment]
@jessfraz @pwittrock  Is there a way to fix this redirect issue?

**Comment by jessfraz** [comment]
where are we hosting now? we can fix this

**Comment by thockin** [comment]
Not as far as I know.

https://kubernetes.github.io is gh-pages, which is configured to believe it has a custom domain, so redirects to it.  But gh-pages doesn't support SSL for custom domains, so it sends to HTTP.  If I get rid of teh custom domain part, some of the automatic redirects gh-pages sends (e.g. .../foo -> .../foo/) end up at github.io domains, rather than our vanity.

http://kubernetes.io is an nginx which automatically upgrades to HTTPS

https://kubernetes.io is that same nginx which proxies https://kubernetes.github.io


The end result is that every connection gets upgraded to HTTPS and goes through the vanity domain.  The downside is the chain of 301s.  Short of getting off gh-pages, I don't know a better answer.

**Comment by thockin** [comment]
Is this causing a problem?  I'm open to other answers, but I don't want to do it for fun..

**Comment by jessfraz** [comment]
oh I didn't realize the first URL is a github owned one, I'm sure they do this on purpose for non-https github pages sites

**Comment by jessfraz** [comment]
I wonder if we swwitched to pure jekyll and not the github pages stuff if we could then implement our own of the automatic redirects github sends (like you said from ../foo -> ../foo/)

**Comment by jessfraz** [comment]
/me runs (really don't think it's worth it)

**Comment by pwittrock** [comment]
We've talked about using netlify for hosting, but it died out.  Would this
address any pain points?

**Comment by jessfraz** [comment]
the redirect would be the same problem afaict, only because we dont control
kubernetes.github.io in terms of how it gets redirected

**Comment by thockin** [comment]
If the docs were hosted somewhere that did SSL at the same time, we
wouldn't need to bounce so much.

**Comment by ahmetalpbalkan** [comment]
> Is this causing a problem?

not a big deal just that at some point in redirection loop security drops to no-TLS. I am not aware if kubernetes.github.io domain is actually used anywhere in the project docs but it seems to have been indexed by Google Search.

**Comment by thockin** [comment]
it redirects to non-TLS and then back to TLS on the right URL.  Was this
triggering an alarm or SEO problem?

**Comment by ahmetalpbalkan** [comment]
@thockin nope, just something I noticed on my address bar. We can close.
