### ISSUE TITLE
Issue with typos in the document

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes.github.io#2580]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**
```
git ls-files | grep -v locale | misspellings -f -
```
The above command can list most of the typos in the document, we can fix all of the issues with the output above.

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@gyliu513 Can you specify a URL? Also, `misspellings` doesn't appear to be a standard shell command&mdash;can you clarify your proposed solution?

**Comment by gyliu513** [comment]
I mean that we can just run the command `git ls-files | grep -v locale | misspellings -f -` and check what should be updated. @zacharysarah

**Comment by zacharysarah** [comment]
@gyliu513 Thanks for clarifying. The `misspellings` command appears to be a [custom shell program](https://github.com/myint/misspellings)--as such, I'm not sure it's viable as a long-term implementation for docs quality at the repo level.

If there are specific typos you'd like to fix, please feel free to open them as separate issues. For now, since there's no specifically actionable doc issue here, I'm closing this issue.
