### ISSUE TITLE
Issue with Guaranteed Scheduling For Critical Add-On Pods by rescheduler

### ISSUE THREAD

**Issue by MJ24** [kubernetes/kubernetes.github.io#2603]
**Related user guide page:**
https://kubernetes.io/docs/admin/rescheduler/

**Problem:**
I have a few problems when using the Critical Add-On Pods.

1: Does this feature only working for Add-On pods? If so, how can I deploy my own service as Add-On to use this feature? I have done these things to make my pods a critical pod:
a) set the namespace as kube-system in the yaml;
b) set the scheduler.alpha.kubernetes.io/critical-pod and scheduler.alpha.kubernetes.io/tolerations fields in the annotations;
c) add a label kubernetes.io/cluster-service: "true" like other Add-Ons do. (Note: please take a look at my rc file below.)
Is this enough? 

2: I tried to fill up my nodes with normal pods first with request limits, and then I tried to deploy my critical pod and set this pod's limits to a value that no node has enough memory to fit this pod, according to user guide page, the rescheduler should remove some non-critical pods on a node to fit this critical pod. But my critical pod just pending there, and when I describe this critical pod, the "Conditions" field has a property "PodScheduled" with value "False" but it doesn't has the property "Reason" which is expect to be "Unschedulable" according to user guide page? How does this happen?

3: I have 3 guesses that why this doesn't work:
 a) The user guide page said that it will reschedule the pods that are already running in the cluster, does this means that it won't work for newly deployed pods?
 b) Does this feature only working for Add-On pods and I haven't I deployed my own pods as Add-On correctly? 
c) I haven't enable/install/start rescheduler correctly? I deployed my k8s cluster just by copying the binaries like kube-apiserver and kubelet in the kubernetes-server-linux-amd64.tar.gz to my master and slave nodes respectively, does this contains the rescheduler?

### The yaml file of my critical pod:
![image](https://cloud.githubusercontent.com/assets/10956360/23251470/71f46a00-f9e8-11e6-9648-13fb5559e733.png)

### The output of of describe that pod:
![image](https://cloud.githubusercontent.com/assets/10956360/23251509/9a6c4638-f9e8-11e6-896e-8321d3fcfebc.png)

1.5.2

**Comment by MJ24** [comment]
@davidopp Could you please take a look?

**Comment by davidopp** [comment]
This feature isn't intended to be used by regular users, only internal Kubernetes infrastructure. We will be getting rid of it in 1.7 and replacing it with a more proper priority and preemption scheme.

@piosz is the expert on this feature, I know he is busy with the 1.6 release so he may not be able to respond to your questions until next week. BTW just for future reference, it's probably better to send this kind of question to the kubernetes-users or kubernetes-dev mailing list; many more people will see it there. We have so many open issues that it's easy to miss them and/or lose track of them.

**Comment by piosz** [comment]
According to what @davidopp wrote you use this feature only at your own risk and you should debug it on your own in such case. Please have in mind that it can cause a mess in your cluster when using inappropriately. We are also in process of migrating tolerations/tains (which is used by rescheduler) feature to beta which may cause even more problems with using rescheduler in your use case.

To briefly answer your questions:
1. You need also a toleration but I can see it in your yaml.
2. To debug this take a look into scheduler (which is responsible for marking pod as unschedulable) and rescheduler logs + into generated events.
3.
a. it will kill some running pods in order to make sure that newly created critical pod can be scheduled properly
b. it's not clear to me what is your definition of addon, assuming you fulfilled all requirements from 1. it should work
c. Rescheduler should work out of the box. Please check /etc/kubernetes/manifests directory on master to verify whether you have its manifest there.

**Comment by MJ24** [comment]
Really thanks for @davidopp and @piosz , and I find the root cause is that my rescheduler pod is running on an agent node which leads to a problem that can not connect to api-server, so I fixed it by making the rescheduler pod only running on the master node.
And looking forward to the more proper priority and preemption scheme in 1.7.
