### ISSUE TITLE
Docker image has old version of Bundler

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes.github.io#2837]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

When I run `docker run -ti --rm -v "$PWD":/k8sdocs -p 4000:4000 gcr.io/google-samples/k8sdocs:1.0` I get the following warning:

```
Warning: the running version of Bundler (1.13.1) is older than the version that created the lockfile (1.13.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

**Proposed Solution:**

1. Update the Docker image regularly.
2. Make the Docker image the "official" way to do builds so that everyone gets the same result.
3. Move the Docker image to a registry/repo where community members have access and can help maintain/push new images.  Hosting this on `gcr.io/google-samples` is not appropriate for a non-Google project.

**Comment by ahmetb** [comment]
I'm planning to make `gcr.io/google-samples` build automatically from the source. It's easy to do so with something like Google Cloud Container Builder,  but it wouldn't be transparent to the community. Otherwise the cleanest solution I can think of is to extract such images to a separate repo and set up Docker Hub automated builds for them. What do you think?

**Comment by jbeda** [comment]
Automatic rebuilds would be nice but aren't necessary IMO.  (and `gcr.io/google-samples` probably shouldn't be used for something that is not google specific).

I think the biggest thing here is to ensure that "official" builds use the same image.  That way we'll be sure that the image is in good working order.

**Comment by ahmetb** [comment]
@jbeda I believe the website is not built by any Docker image for PROD; instead GitHub pages automatically builds Jekyll pages. If I understand correctly, the staging container is offered on a best-effort basis (I don't think there's any guarantee that you'll get the same build output.)

Currently many `gcr.io/google-samples/*` are used in various places across the tutorials and samples. I think we offer public images somewhere for a more convenient getting started experience with Kubernetes. We should make sure that all Dockerfiles of such images are open as well. Other than that, where would you like to see the images being uploaded for convenience? Docker Hub? If there's any community interest, I'm eager to help in a community-maintained public registry effort.

As for the staging image, you can build it from [Dockerfile](https://github.com/kubernetes/kubernetes.github.io/blob/master/staging-container/Dockerfile). We probably offer it on gcr.io just so that we have a single-liner command for convenience.

**Comment by ahmetb** [comment]
I believe this warning now went away as I manually pushed v1.1 (and updated the docs) for the staging image. Let's close the issue, feel free to open a separate issue to track hosting images on a more open/transparent medium. It's something I want to look at soon as well.
