### ISSUE TITLE
Broken download links in /docs/tasks/kubectl/install/

### ISSUE THREAD

**Issue by devent** [kubernetes/kubernetes.github.io#2921]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

Section Install kubectl Binary Via curl shows a broken link in curl commands.
```
$ curl -LO https://storage.googleapis.com/kubernetes-release/release/$\(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt\)/bin/linux/amd64/kubectl
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>%                                                  
```

**Proposed Solution:**

Update the download links.

**Page to Update:**
http://kubernetes.io/docs/tasks/kubectl/install/

**Comment by vbmade2000** [comment]
@devent I was able to download using 
`
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl`

I think you are facing issue because of extra "\" in `release/$\(curl -s` and `stable.txt\)` part.

**Comment by gayanjay** [comment]
@devent : I can download the `kubectl` as http://kubernetes.io/docs/tasks/kubectl/install/. 
As @vbmade2000  said you have additional `\` in your url.
if you copy and paste the URL to the terminal. The terminal adds extra `\`.  please remove those manually. you should be good. I hope we can close this issue.
