### ISSUE TITLE
How to set aws ebs provider for kubernetes

### ISSUE THREAD

**Issue by show168** [kubernetes/kubernetes.github.io#2931]
I want to user kubernetes awsElasticBlockStore. It needs to set aws credentials in installing kubernetes.  How to set it?  

The kubelet log is:
error: failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0304f57235e93a1a7: error listing AWS instances: NoCredentialProviders: no valid providers in chain
Mar 21 03:21:54 ip-172-31-5-171.cn-north-1.compute.internal systemd

**Comment by php-coder** [comment]
This is an issue tracker of the site and not the kubernetes itself. If you ask in more appropriate place then most likely you will get an answer. If you're following one of the guides from the site and feel that this guide maybe improved then it would be good to mention this guide.

Anyway this information isn't enough to help you, because it's not clear how do you run kubernetes.

**Comment by zacharysarah** [comment]
@show168 I encourage you to ask your question in the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/). As this issue doesn't specifically address a doc bug, I'm closing it.
