### ISSUE TITLE
Fix vagrant based cluster setup

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes.github.io#303]
The current vagrant based cluster setup does not work reliably on OS X. 
Until we identify issues and fix it, I plan on removing that guide from kubernetes.io

cc @janetkuo @pwittrock

**Comment by pwittrock** [comment]
+1

**Comment by MHBauer** [comment]
#405, #481, #482, #490, & #502 are dups caused by #294. 

I wouldn't mind helping with the docs, if only to have them for my own attempts at local development. I don't have a cluster to run on. I think there's probably two types of users of a local vagrant cluster, those kicking the tires, and those trying to do development.

@mikebrow cause he was looking at the vagrant docs.

**Comment by jaredbhatti** [comment]
We use minikube: http://kubernetes.io/docs/getting-started-guides/minikube/
Vagrant is deprecated: https://github.com/kubernetes/community/blob/master/contributors/devel/local-cluster/vagrant.md
