### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by bostone** [kubernetes/kubernetes.github.io#3159]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When attempting to run "kubeadm init" step preflight fails with this message:
```
Some fatal errors occurred:
        /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
```
**Proposed Solution:**
Add "sysctl" call reference to the manual (if that is indeed the way to fix this) 

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/kubeadm/

1.6.0

**Comment by bostone** [comment]
Actually this is really bad. Even setting bridge-nf-call-iptables=1 doesn't solve the problem. The "kubeadm init" runs to this line and then hangs indefinitely

`[apiclient] Created API client, waiting for the control plane to become ready`

**Comment by bostone** [comment]
I think this is problem with 1.6.0 release. The previous version worked reliably but not anymore

**Comment by bostone** [comment]
Yes indeed, kubeadm is currently broken https://github.com/kubernetes/kubernetes/issues/43815

**Comment by zacharysarah** [comment]
@bostone Thanks for opening this issue. It looks like the underlying issue was resolved, so I'm going to close this issue. Please feel free to re-open it if you notice similar behavior. 👋

**Comment by houami** [comment]
still getting an error with kubeadm 1.7.4

**Comment by naseemkullah** [comment]
im getting the error with 1.7.5  on centos 7

**Comment by naseemkullah** [comment]
for redhat family nodes: if you've disabled selinux and not yet rebooted the node (not mentioned in k8s docs to do so) then please do it. 

after that, that error was gone, but as mentioned by someone above, now dealing with:

"[apiclient] Created API client, waiting for the control plane to become ready"

**Comment by zacharysarah** [comment]
@heckj 👋

**Comment by naseemkullah** [comment]
Hey in the end the error was that kubelet was not in an "ok" state due to a mismatch with docker in terms of cgroup driver.

By editing /etc/systemd/system/kubelet.service.d/10-kubeadm.conf with the cgroup driver that matches docker :
```#Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"```
, running a systemctl daemon-reload, and finally restarting the kubelet service, it is in an "ok" state.

**Comment by heckj** [comment]
thanks @naseemkullah - was there an error in the getting started, or something we simply just didn't specify, that would have helped make sure the relevant versions were aligned?

**Comment by naseemkullah** [comment]
np @heckj , well the rebooting after selinux is disabled was not mentioned in the docs unless i missed it. As for the kubelet not being ok due to mismatch of docker and kubelet cgroup drivers, this may be caused due to the fact that i used latest versions of both components, even though it was recommended to use an older version of docker. but once i set kubelet's cgroup driver to be the same as docker's, kubeadm init worked like a charm. Hope that helps, if not please let me know.

**Comment by naseemkullah** [comment]
@heckj  if this helps at all, here are the ansible tasks used to deploy kubeadm on centos7 successfully, please take note of the "reboot node" handler called when selinux is disabled.
https://github.com/naseemkullah/mp-roles/blob/master/install-kubeadm/tasks/main.yml

**Comment by heckj** [comment]
Thanks @naseemkullah 

I'm traveling at the moment, but will keep this open and assigned to me to update the CentOS related installation docs to make a mention of the need for a reboot after disabling SELinux.

**Comment by heckj** [comment]
PR up, the documentation I think you were originally referencing is now deprecated, but I went ahead and made a note about the need to reboot for SElinux disabling on CentOS. I also found some broken links and resolved those in the same PR.
