### ISSUE TITLE
Issue with /docs/tutorials/connecting-apps/connecting-frontend-backend/

### ISSUE THREAD

**Issue by metachris** [kubernetes/kubernetes.github.io#3242]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

The documentation uses `apiVersion: apps/v1beta1` for Deployments, which results in the following error:

```
$ kubectl create -f http://k8s.io/docs/tutorials/connecting-apps/hello.yaml
error: error validating "http://k8s.io/docs/tutorials/connecting-apps/hello.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
```

**Proposed Solution:**

Change to `apiVersion: extensions/v1beta1`

**Page to Update:**
https://kubernetes.io/docs/tutorials/connecting-apps/connecting-frontend-backend/

**Comment by ahmetb** [comment]
@metachris  this is because your client is v1.6 and server is v1.5. In v1.6, Deployment object is moved to apps/v1beta1. [[changelog]](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deployment-2) The yaml file you have uses apps/v1beta1 for Deployment but this doesn't exist on the server. I recommend upgrading your server or downgrading your client. (or just changing the `apiVerison` in yaml file)

**Comment by metachris** [comment]
Oh wow, thanks for the info! My bad ^^
