### ISSUE TITLE
Invalid hyperlink of command.

### ISSUE THREAD

**Issue by warmchang** [kubernetes/kubernetes.github.io#3398]
**This is a Bug Report** 

- [x] Bug Report

**Problem:**
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/minikube.md
There are some invalid hyperlink of minikube command, because the following PR&Issue:
https://github.com/kubernetes/minikube/pull/1356
https://github.com/kubernetes/minikube/issues/1338

**Proposed Solution:**
We should host the command manual somewhere, and change the hyper link of "minikube.md" file.

**Comment by ahmetb** [comment]
@aaron-prindle do you have any guidance here?

**Comment by aaron-prindle** [comment]
We have removed the auto-generated CLI documentation for now.  We are in the process of refactoring our docs https://github.com/kubernetes/minikube/pull/1410 and removing the relative links in our readme so that we can better automate updating the kubernetes.github.io page.  I have for now submitted a PR removing the hyperlinks from the kubernetes.github.io page: #3605

**Comment by ahmetb** [comment]
@aaron-prindle thanks!

**Comment by jaredbhatti** [comment]
Closing this issue!
