### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by feborges** [kubernetes/kubernetes.github.io#3573]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

I created the cluster with this manual ( https://kubernetes.io/docs/getting-started-guides/kubeadm/ ). when I ran the command kubectl get pods --all-namespaces, I saw the error below.

kube-system   kube-dns-3913472980-l9lcv       0/3       rpc error: code = 2 desc = failed to start container "78c83884781e0b0154b9594c84b66b033d4906b8f2e88d255d0fbe8071f41f27": Error response from daemon: cannot join network of a non running container: 8f82c6e5f9548611201ab1ca5b50a45d3084ecc96561c463c8c526ef1c5b8423   8613       1d

The cluster has 1 master and 2 nodes.

$ kubectl get nodes
NAME      STATUS    AGE       VERSION
kube1     Ready     1d        v1.6.1
kube2     Ready     1d        v1.6.2
kube3     Ready     1d        v1.6.2

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
Hello @feborges, it looks like you have a question rather than a bug report about the documentation. You have a better chance of getting help in asking your questions in one of the Kubernetes help channels listed below (sorted by activity amount). We are not well-equipped to answer these questions.

- :shipit: **Slack:** http://slack.k8s.io/ (`#kubernetes-users` or `#kubernetes-novice channels`)
- 📫  **Mailing list:** https://groups.google.com/d/forum/kubernetes-users
- 🥇   **Stack Overflow:** http://stackoverflow.com/questions/tagged/kubernetes

If you ask your question on the forums above, please consider closing this issue.
