### ISSUE TITLE
Automated header link checking

### ISSUE THREAD

**Issue by techtonik** [kubernetes/kubernetes.github.io#4004]
**This is a...** 
- [x] Feature Request

**Problem:**
When chapters/pages are removed, documentation links become broken.

**Proposed Solution:**
Run link checker that indexes and understands markdown headers.

https://github.com/kubernetes/kubernetes.github.io/pull/4001#issuecomment-306567432 (chapter removed, no test failures)
https://github.com/kubernetes/kubernetes.github.io/issues/734 (generic link checking)

**Comment by zacharysarah** [comment]
@techtonik 👋 Thanks for opening this issue. Because #4001 was closed without any visible changes, the result is that this issue duplicates #734. On the basis of duplication, I'm closing this issue. If you encounter any other broken links, please feel free to open an issue that lists them specifically.
