### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/expose-external-ip-address/

### ISSUE THREAD

**Issue by shay-berman** [kubernetes/kubernetes.github.io#5367]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
I run the flow in the https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/
#> kubectl run hello-world --replicas=5 --labels="run=load-balancer-example" --image=gcr.io/google-samples/node-hello:1.0  --port=8080
#> kubectl expose deployment hello-world --type=LoadBalancer --name=my-service

but the external-IP is in pending state for long long time.

**Proposed Solution:**
not sure
is it possible to create external-IP address for service without using type ingress? and if so how?

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

k8s version 1.6.1

**Comment by heckj** [comment]
thanks for the report @shay-berman !

Some of these tutorials are running minikube on a VM, with a browser-based terminal interface to where they're hosted. This tutorial is assuming you have a Kubernetes cluster in an environment that does support a load-balancer - such as AWS, Azure, or GKE. If you're doing this tutorial with minikube or another local cluster setup that doesn't have a LoadBalancer resource available, you'll see exactly what you're seeing now.

In a minikube type setup, the cluster is all on a single VM - and where you have access to the underlying hosts that make up the cluster, you can alternatively use "NodePort" to expose services. (so `type=NodePort` instead of `type=LoadBalancer`). The resulting command still creates a service, and handles all the forwarding/proxy mechanisms using the instance of proxy that's running on each of the nodes within the cluster.

So hopefully that answers your question - about "how does this work". As for the tutorial, could you tell me where you were trying to run it?

**Comment by heckj** [comment]
(removed team/katacoda label since it's not related to the externally hosted/interactive tutorials)

**Comment by shay-berman** [comment]
thanks @heckj

closing tge issue
