### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/vsphere/

### ISSUE THREAD

**Issue by g1001p** [kubernetes/kubernetes.github.io#5477]
Hello dear forum,
I am working with k8s version 1.6.8 that configured with vSphere cloud provider implementation. In my use case the worker nodes have same size from CPU, RAM, OS resources perspectives. Also the workers are distributed evenly cross the ESX machines in order to create homogeneous workers infrastructure as much as possible. During cluster workload i observed situation while one of ESX machines got 100 % of memory utilization and it's committed all the memory to the running guested VMs over-there.
In the same time and from the guested VMs perspectives the memory utilization was around 50-60%.
My understanding from all this observations that kubernetes is not aware that ESX memory is already exhausted and next memory claims of VM could cause to intensive swapping and performance degradation.    

**This is a...** 

- [ ] Feature Request
Maybe i am not a first person who raised such issue. Probably you have some recommendations how to handle this issue via k8s cluster. I guess it will be good option to provide kuberenetes with awareness about ESX resources where workers are running.  
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@heckj :wave: This one looks like it may be an underlying issue rather than one specific to the tutorial itself.

**Comment by heckj** [comment]
removing the `team/katacoda` since it's not related to the interactive/hosted online tutorials.

That said, @g1001p thank you for the report and the question!

I would definitely recommend that if you're using Kubernetes on VMs inside of ESX, that you do not allow for oversubscription of those VMs within the ESX environment. You are quite correct in that Kubernetes doesn't natively know anything about the underlying host's memory and when oversubscription can lead to exhaustion. In those case, the result will be exactly as you've described, with the ESX server hitting swap extensively and having a very high number of page faults.

The community usage of vSphere has a few folks mentioned at https://kubernetes.io/docs/getting-started-guides/vsphere/ - perhaps one of them has a suggestion as well?

/cc @abrarshivani 
/cc @kerneltime
/cc @BaluDontu
/cc @luomiao
/cc @divyenpatel

**Comment by BaluDontu** [comment]
Hi @g1001p. Right now we don't have control over the ESX host resources like memory etc for scheduling decisions. Kubernetes scheduler takes into account memory and CPU usage details on nodes for pod provisioning.

The best possible way to overcome this problem would be to use a dedicated resource pool for your kubernetes cluster where you can set memory and CPU for resource pools. This way you kubernetes cluster always has the required set of resources. Take a look at our vSphere cloud provider documentation for best practices - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/bestpractices.html.

**Comment by heckj** [comment]
@g1001p thank you for your issue and the feedback. We are going to close this issue for now, but feel free to re-open if there is a specific documentation issue to address. You can also reach us on the sig-docs channel of [Kubernetes slack](http://slack.k8s.io)

**Comment by g1001p** [comment]
Thank you guys for the information.
BR
Grigory
