### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by bcbcarl** [kubernetes/kubernetes.github.io#5876]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
```
$ kubectl proxy
$ http://localhost:8001/api/v1/proxy/namespaces/default/pods/kubernetes-bootcamp-2378835682-vt8nh/
Error: 'dial tcp 172.17.0.4:8000: getsockopt: connection refused'
```

**Proposed Solution:**
Fix connection issue
or
Use `kubectl expose deployment`.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Kubernetes Version:**
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-10-05T00:41:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional Information:**
```
$ kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     <none>    50m       v1.7.5

$ kubectl get deployments
NAME                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kubernetes-bootcamp   1         1         1            1           46m

$ curl http://localhost:8001/version
{
  "major": "1",
  "minor": "7",
  "gitVersion": "v1.7.5",
  "gitCommit": "17d7182a7ccbb167074be7a87f0a68bd00d58d97",
  "gitTreeState": "clean",
  "buildDate": "2017-10-06T20:53:14Z",
  "goVersion": "go1.8.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}

$ export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
$ echo Name of the Pod: $POD_NAME
Name of the Pod: kubernetes-bootcamp-2378835682-vt8nh
```

**Comment by heckj** [comment]
Thanks for the report @bcbcarl  - was this with the interactive, browser-based tutorial or on your own instance using Minikube (or another instance of a kubernetes cluster?)

I'm guessing your own minikube - and if you don't mind me asking, which version of minikube were you using?

**Comment by bcbcarl** [comment]
This is on my local Minikube v0.22.3.

**Comment by heckj** [comment]
Thanks @bcbcarl  - this has worked in previous versions, so there's a regression somewhere in this mix that I haven't yet hunted out. I did just replicate what you're seeing on my local machine. 

If you do this same set of actions in the interactive tutorial (which uses an older version of kubectl and server), the proxy commands do work - although they need two terminal windows to operate (one for running the proxy, another for the curl commands).

I've also now noticed that if you wait just a bit, the proxy starts to operate correctly - I don't know what's causing the delay in activation, but after ~30 seconds or so, it was working for me. I'll see if i can open a bug that highlights this in https://github.com/kubernetes/kubernetes (or maybe minikube) - as I think this is a regression in some form rather than a documentation bug.

Exposing the service will definitely "work" to make it available - and there's another module in the tutorial sequence that is explicitly set up to do just that. This section was specific to showing you how you can use `kubectl proxy` to get access to your Pod through the API server proxy mechanisms.

**Comment by bcbcarl** [comment]
Thank you very much for your explanation. 😃

**Comment by Madhav1217** [comment]
hi Frds i tried kubernetes deployment through jenkins via terraform files i got this type of error please help me
04:42:20 * kubernetes_deployment.polaris-administration: Failed to create deployment: Post http://localhost/apis/apps/v1/namespaces/default/deployments: dial tcp [::1]:80: connect: connection refused
