### ISSUE TITLE
pods scheduled on different node can not communicate with each other

### ISSUE THREAD

**Issue by k19810703** [kubernetes/kubernetes.github.io#5878]
I created my cluster(k8s 1.8) by kubeadm on 2 physical server( os:ubuntu 16.04)

$ kubectl get nodes
NAME STATUS AGE VERSION
digital Ready 21m v1.8.0
next Ready 22m v1.8.0
$ kubectl get pods
NAME READY STATUS RESTARTS AGE
wordpress-76b66d5644-76rtc 1/1 Running 4 7m
wordpress-mysql-5cdbc78858-vxnmn 1/1 Running 0 7m

By following this guide , I tried to deploy it on my cluster. WordPress pod was deployed on master node , and mysql pod was deployed on another worker node.

But wordpress pod can not connect mysql.

$ kubectl logs -f wordpress-76b66d5644-76rtc

MySQL Connection Error: (2002) No route to host

Warning: mysqli::mysqli(): (HY000/2002): No route to host in - on line 22

Warning: mysqli::mysqli(): (HY000/2002): No route to host in - on line 22

**Comment by heckj** [comment]
Thanks for the report @k19810703  - you're reporting this to the documentation issue repository, so this may not get entirely the attention you'd like. I presume you were also following the example/tutorial at https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/ based on the pod names.

If I may ask, what network option did you use or install with kubeadm when you set up your two-node k8s cluster?

As a more general diagnostic question, the demo at https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/ focuses on using the service exposure between the Pods, so could you provide the output of `kubectl get services`? I don't honestly expect this is an issue, but it doesn't hurt to double check to make sure you set up the service.

If you were following a different example or tutorial, that would also be useful to know.

**Comment by k19810703** [comment]
thanks for your reply.
I installed calico for pod network by using below command
sudo kubeadm init --pod-network-cidr=192.168.0.0/16
kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

BTW,I am following https://github.com/IBM/Scalable-WordPress-deployment-on-Kubernetes to do this exercise.I have changed my cluster for other exercise so I can't get the same output of "kubectl get service"  as problem happend. But returns just like the below but ip address is different. 

$ kubectl get svc wordpress
NAME        CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
wordpress   10.10.10.57   <nodes>       80:30180/TCP   2m

I also don't thinks it is an issue , I just would like to get some hit about how to fix my problem or how to trouble shooting it.

**Comment by heckj** [comment]
hi @k19810703,

I'm not an expert on diagnosing the network layer, but it sound like Calico isn't working for your environment. Calico, as I understand it (which could easily be incorrect) does rely on network hardware to help make the routing connections between the physical hosts - so is a BGP based mechanism with your switches isn't something you can arrange, then a different network option may be advisable.

If you're using a home network, or office network where you're not also the network administrator, then I'd personally recommend you look at Flannel or one of the other overlay network options. (And yes, I think this means you'll likely need to reinstall your cluster to get this to work).

As for more and better instructions on how to debug the networking layer of this, I'd recommend looking into the Kubernetes Slack and seeing if there's someone available in either the general channel, or the calico/networking channel there that can offer more sage advice. The other obvious option is checking with the Calico project itself - I'm not sufficiently familiar with it to recommend a specific avenue where you might get assistance. StackOverflow might also have some options related to installing on bare metal with Calico that are worth searching for.

The issues in this repo are focused primarily on documentation issues with the content hosted at https://kubernetes.io/, including our tutorials and reference documentation. Opening issues in the repository https://github.com/kubernetes/kubernetes/issues is more appropriate for reporting bugs on Kubernetes in general, and although it's also not a support channel you may get more assistance there.

Since this isn't an issue related to https://kubernetes.io/ content, I'm going to go ahead and close this issue for now. If you do have a specific documentation issue, please re-open this or open another issue so we can help you resolve it.
