### ISSUE TITLE
UI Icons

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/kubernetes.github.io#789]
### About

A few [benefits of icons](https://www.nngroup.com/articles/icon-usability/) include:
- Speed of recognition
- Visual appeal
- Compact size

For these reasons, we would like to incorporate them into Dashboard. 
### Proposal

From the [Github repo](https://github.com/google/material-design-icons): "Material design icons are the official icon set from Google that are designed under the material design guidelines." You can view the full list [here](https://design.google.com/icons/).

The Material design icon set is growing all the time, but it's likely we'll need to design custom icons for our Kubernetes-specific needs.
1. Decide what UI items we want icons for. We'll begin with the top-level menu items from [Left-hand Navigation Hierarchy #908](https://github.com/kubernetes/dashboard/issues/908).
   - Nodes
   - Namespaces
   - Persistent Volumes
   - Overview
   - Workloads
   - Services
   - Storage
   - Config 
   - Policies
2. Assess which menu items we might be able to use existing Material design icons for. Either from the [official set](https://design.google.com/icons/), or from a trusted paid set such as [NOVA](http://www.webalys.com/nova/).
3. Conceptualize & sketch for those menu items we can't find a suitable existing icon for.
4. Execute SVG icons based on agreed-upon sketches, using as a guide the [Material design icon principles](https://material.google.com/style/icons.html#icons-system-icons).

Note: there will be some overlap between this issue and [Symbols for Diagrams #747](https://github.com/kubernetes/kubernetes.github.io/issues/747), but #747 is focused more on the display setting of _docs_, and thus its visualizations can be larger / more complex, and will strive to incorporate the relationships between components.

**Comment by romlein** [comment]
Based on the call this morning with @bryk and a few Fujitsu folks, I've screenshotted and put in an InVision prototype several [existing  Material icons](https://invis.io/9E7X5VO4K) I think could potentially be a good fit for Dashboard's needs. Add there any comments you'd like to share! 

Concepts we talked about for our top-level menu items:

- Nodes
  - Servers.
  - Compute power.
- Namespaces
  - A box to hold objects.
  - Dividing up somethign into smaller sections.
  - A family name (surname) as representative of a certain grouping.
- Persistent Volumes
  - Storage with a lock to show that it doesn't change with time.
- Overview
  - Eye.
  - Dashboard.
- Workloads
  - Something that has work applied to it.
  - Code that gets run (binary values).
- Services
  - Exposing applications to the world. Revealing; uncovering.
- Storage
  - Database.
- Config
  - Configuration _of applications_. 
- Policies
  - What's allowed / what's not allowed.

**Comment by digitalfishpond** [comment]
Initial suggestions for icons (result of brainstorm with @bryk, @maciaszczykm, @floreks, @PiotrDabkowski, @digitalfishpond  -- descriptions added for reference, though nicely synthesised by @romlein in previous comment - slight variation on the explanation for workloads, and we didn't get round to 'Overview'):

**Namespaces**: boxes/bags where you put your things, they can have names, you cannot put some things into a red box. A family name. One thing must have exactly one namespace. 
![ui_namespaces](https://cloud.githubusercontent.com/assets/13361549/16760592/c61292de-481c-11e6-8227-1091eee39e20.jpg)

**Nodes**: individual computers in your cluster 
![ui_nodes](https://cloud.githubusercontent.com/assets/13361549/16760687/36612c3a-481d-11e6-84a1-1eab069e1ba7.jpg)

**Persistent Volumes**:  attached to a cluster, the same as nodes, programs can use them.
![ui_persistentvolumes](https://cloud.githubusercontent.com/assets/13361549/16760745/8dff5624-481d-11e6-89f8-458eccdb0a06.jpg)
![ui_persistentvolumes2](https://cloud.githubusercontent.com/assets/13361549/16760750/91e80b0a-481d-11e6-88d5-a1da0e9e7fc4.jpg)

-------------------------------------------------------------------------

**Workloads**: there are different workloads, whenever you want to run something, that something is the workload. Robot. The actual work rather than the thing that does the work. Unit of computation. Weights/dumbells, binary 01000111010110, gears/cogs...
![ui_workloads](https://cloud.githubusercontent.com/assets/13361549/16760845/013e6ee0-481e-11e6-8964-1e48b56013f0.jpg)
![ui workloads2](https://cloud.githubusercontent.com/assets/13361549/16761067/dfd0d33c-481e-11e6-9c56-e0f96ffdfc29.jpg)

**Services**: something for data exchange, the thing used for connecting/exposing your apps - a globe and a cloud connected?
![ui_services](https://cloud.githubusercontent.com/assets/13361549/16760947/543a21fc-481e-11e6-9830-6e7802fec751.jpg)

**Storage**: Classical database, can use Persistent Volumes, but is temporary / lasts the lifetime of the cluster only.
![ui_storage](https://cloud.githubusercontent.com/assets/13361549/16761002/8fd5eb56-481e-11e6-9b1a-9d8204096ef0.jpg)

**Config**: Configuration of your apps running in the Cloud, (as opposed to configuration of the User or of Dashboard etc...)
![ui_config](https://cloud.githubusercontent.com/assets/13361549/16761056/d0e5006e-481e-11e6-96c5-281e67c8376a.jpg)

Policies: Configure your namespaces, What is allowed/not allowed.
![ui_policies](https://cloud.githubusercontent.com/assets/13361549/16761139/2bc6df34-481f-11e6-827b-0777b8f9065d.jpg)

**Comment by bryk** [comment]
@bgrant0607 @pwittrock @janetkuo This is @romlein's prototypes for UI icons: https://projects.invisionapp.com/share/9E7X5VO4K#/screens/173096021/comments

Take a look and comment if this is something we can use in docs/upstream

**Comment by romlein** [comment]
@bryk @digitalfishpond thoughts on this updated icon selection?
Also see [comment #5](https://invis.io/XZ7RITOQD#/175069092_Expanded_w_Icons-_Indented) discussing persistent volumes and the best icon there.

**Comment by bgrant0607** [comment]
@romlein Thanks much. Some comments:

* I like the services icon.
* The lock icon would make the most sense for security settings or secrets, rather than Persistent Volumes.
* PersistentVolumes should look similar to storage volumes used by pods, but distinct in some way. We are using the standard cylinder representation for storage volumes used by pods in documentation diagrams. I like the infinity symbol -- maybe put it on top of the cylinder?
* I like the vertical bars for namespaces. I don't know what the box is supposed to represent, but it looks too similar to the node icons.
* I'd avoid using gears for Config. I could imagine a standard-looking settings icon for settings of the UI itself. We've also (unfortunately) used gears in pod icons in presentations, which may generate confusion. Something more like a [survey icon](https://www.google.com/search?q=survey+icon&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiT4q-Io4XOAhVN0GMKHccjBAsQsAQIHQ&biw=1294&bih=802) might make sense for config -- choosing options.
* Workloads is a tough one. In doc diagrams, we're experimenting with a circular arrow, to represent a control loop, for controller types, such as Deployment, ReplicaSet, etc. I'm not attached to it, but a simple shape seems better than ones where users may struggle to understand what it's supposed to represent, such as with all the proposed icons other than the barbells.

**Comment by romlein** [comment]
Thanks for the feedback @bgrant0607! I've updated the [InVision](https://invis.io/9E7X5VO4K#/173096021_K8s-Icons) with a few existing Material icons based on your suggestions.

Responding to a few of your comments:
 - PersistentVolumes I've added a rough concept for what that could look like if we want it related to Storage. That I think would have to be a custom icon – I haven't found anything existing.
 - For Namespaces: the idea behind the dotted line was a virtually bounded-off, exclusive box, but I can see how it might be too similar to the Nodes icon. I've included two other versions that are more visually distinct if we like the dotted line pattern.
 - Workloads definitely seems to be a challenging concept to represent! The circular arrow has such a strong historic meaning as "Restart / Refresh" that I think trying to re-wire users' perception could prove too challenging.

If you toggle on "Comments" in the lower RH corner of InVision then select a comment point you can check out some of the discussion that's been going on there.

**Comment by romlein** [comment]
How closely do we want to align / not conflict with Google Cloud Platform as far as icons? After reviewing the icons in use by Google Cloud Platform, I'm wondering if we should reconsider some of ours like "Nodes", which is nearly identical to what GCP uses for "Compute Engine."

![compute](https://cloud.githubusercontent.com/assets/5114858/17110952/5f1d9a1e-526d-11e6-9ee5-3eef821305bb.png)

/ @bryk @pwittrock

**Comment by bryk** [comment]
> How closely do we want to align / not conflict with Google Cloud Platform as far as icons?

I guess that we should not have the same icon for different concepts. Just to avoid confusion. Other than that, we can use similar icons. 

How about we come back to the idea of a computer tower for nodes? Like [this](https://www.google.com/search?q=computer+tower+icon&espv=2&biw=1440&bih=829&tbm=isch&imgil=GLQKPShRo3-YpM%253A%253BEP1o0e7nH4aITM%253Bhttps%25253A%25252F%25252Fthenounproject.com%25252Fterm%25252Fcomputer-tower%25252F176244%25252F&source=iu&pf=m&fir=GLQKPShRo3-YpM%253A%252CEP1o0e7nH4aITM%252C_&usg=__qpJpguHCf82ThT7STXQSbPt_By8%3D&ved=0ahUKEwj79-2HrZTOAhVD72MKHcdIBl8QyjcIPg&ei=6QeZV7vfIcPejwPHkZn4BQ#imgrc=GLQKPShRo3-YpM%3A)

**Comment by romlein** [comment]
After extensive research, I'm advocating we _not_ go ahead with icons for the UI initially.
Rationale for this decision:
 - Icons are time and effort intensive to create, and those resources would be better put toward other more fundamental aspects of Dashboard at this stage. 
 - Our concepts in need of icons are so complex and abstract we'd necessarily be introducing some new patterns to users that we expect they learn. In these fluid, fast-changing initial stages of the project, I think it's risky to commit to icons, and if we change them we've lost a lot of their value. 
 - While they would be nice to someday include so that we can have a collapsible side nav, that's a "nice to have" and not a high priority at the moment.
 - Excluding icons was agreed upon as the best initial course of action by Keith Guerin (GCP UX Designer), Nick Botner (GCP Creative Director), and Aaron Wheeler (Google Ads UX Designer).

**Comment by bryk** [comment]
Yes. Makes total sense. We'll revisit this at appropriate time.

**Comment by jaredbhatti** [comment]
I'm going to close this issue for issue hygine's sake.  Please reopen if it's still valid.
