### ISSUE TITLE
Per-file OWNERS

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes.github.io#874]
Forked from #739

The OWNERS mechanism in the main repo is directory-based. However, we have many docs with different technical content side by side. Therefore, we need a file-based OWNERS mechanism for automatic PR assignment. #739 suggested representing owners in doc front-matter.

Tests need sub-file owners, but it doesn't look like that mechanism would fit the doc use case very well.

cc @kubernetes/contributor-experience @kubernetes/kubernetes-docs-maintainers

**Comment by Kashomon** [comment]
I agree that a per-file OWNERS is probably necessary, but I think it would still be useful to restructure many of the guides into directories. There are already implicit groupings that the flat directory structure is hiding.

**Comment by bgrant0607** [comment]
@Kashomon I'm fine with adding structure, though we need to be careful to not break existing URLs. We will break everything when we do the overhaul, but we need to avoid repeatedly breaking links, which we've not been great about.

**Comment by bgrant0607** [comment]
@foxish Many of the documents were copied from the kubernetes repository in a way that didn't preserve git history.

Compare:
https://github.com/kubernetes/kubernetes.github.io/blame/master/docs/user-guide/configmap/index.md

with:
https://github.com/kubernetes/kubernetes/commits/master/docs/user-guide/configmap.md

We'll need to extract the original authors from the kubernetes repository.

Also, it would be useful to support both per-directory and per-file owners. We'll want to be able to easily cover files that are part of the site layout and navigation, for instance, such as:

https://github.com/kubernetes/kubernetes.github.io/tree/master/_includes

**Comment by foxish** [comment]
@bgrant0607 What is the long-term plan with the generation of OWNERS? Is it to generate them once and then let the OWNERS themselves maintain it, or to maintain and re-run the script from time to time to update the lists?

**Comment by bgrant0607** [comment]
@foxish I expect we'll generate it once and then curate it manually thereafter, but we do have several more repositories we need to generate OWNERS information for, and there will likely be new repositories donated in the future that we'll need to generate OWNERS information for.

**Comment by foxish** [comment]
The current way in which coreos/findowners operates is to take the top N committers over the last 6 months. However, as we saw in case of contrib/, it missed some owners who had committed the original file, because they hadn't contributed in over 6 months.

I think we can fix this in one of the following ways:
1. Going over the entire commit history instead of just the last 6 months
2. Using the last 6 months, but also adding the original author to the list of owners.
3. Looking at a fixed number of commits prior to HEAD and pick top N committers from that.

I can tell at least on the docs side that the older docs may not have had any substantial changes in a while and using the 6 months criterion definitely wouldn't suffice there.

**Comment by foxish** [comment]
Closing as this is done.
